# Generated by Django 5.2.6 on 2025-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
